### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by aig787** [tikue/rust-ml#1]
Compiling ml v0.1.0 (file:///home/aaron/Git/rust-ml)
     Running `rustc src/lib.rs --crate-name ml --crate-type lib -g -C metadata=426abd62023c69d9 -C extra-filename=-426abd62023c69d9 --out-dir /home/aaron/Git/rust-ml/target --emit=dep-info,link -L dependency=/home/aaron/Git/rust-ml/target -L dependency=/home/aaron/Git/rust-ml/target/deps`
src/plots/plot.rs:15:15: 15:16 error: expected one of `(`, `+`, `::`, `;`, or `]`, found `,`
src/plots/plot.rs:15     rows: [Row, ..NUM_ROWS],
                                   ^
Could not compile `ml`.

Caused by:
  Process didn't exit successfully: `rustc src/lib.rs --crate-name ml --crate-type lib -g -C metadata=426abd62023c69d9 -C extra-filename=-426abd62023c69d9 --out-dir /home/aaron/Git/rust-ml/target --emit=dep-info,link -L dependency=/home/aaron/Git/rust-ml/target -L dependency=/home/aaron/Git/rust-ml/target/deps` (status=101)

I'm using the 1.0 alpha build of Rust

**Comment by tikue** [comment]
Sorry, not sure why I didn't see this sooner -- I'll update this code for 1.0-alpha soon.

**Comment by tikue** [comment]
Master is now updated to alpha!
